# #####################################################################
# Automatically generated by qmake (2.01a) Tue May 12 19:26:45 2009
# #####################################################################
TEMPLATE = app
TARGET = qtimageskel
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += glwidget.h \
    sphere.h \
    window.h

FORMS += MainWindow.ui 

SOURCES += glwidget.cpp \
    main.cpp \
    window.cpp \
    sphere.cpp


QT += opengl
